name: Gerar APK do Nubank Clone

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Baixar dependencias
        run: flutter pub get

      - name: Compilar APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Disponibilizar o APK
        uses: actions/upload-artifact@v4
        with:
          name: aplicativo-nubank
          path: build/app/outputs/flutter-apk/app-release.apk
          
