name: Gerar APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Baixar dependencias
        run: flutter pub get

      - name: Compilar APK (Ignorando checagem de versao do Gradle)
        run: flutter build apk --debug --no-tree-shake-icons --android-skip-build-dependency-validation

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: meu-app-nubank
          path: build/app/outputs/flutter-apk/app-debug.apk
          
